# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JO_JTisH8yvc2bTYKdhh6xQ4Oi2BC_kQ
"""

import streamlit as st
import numpy as np
import joblib

# Load the trained model
model = joblib.load('price_range_model.pkl')  # Make sure this path points to your saved model

# Streamlit App Title
st.title("Mobile Price Range Prediction")

# Create input fields for all the required features
battery_power = st.number_input("Battery Power (mAh)", min_value=500, max_value=3000, step=100)
blue = st.selectbox("Bluetooth Enabled", (0, 1), help="0 = No, 1 = Yes")
clock_speed = st.slider("Clock Speed (GHz)", min_value=0.1, max_value=3.0, step=0.1)
dual_sim = st.selectbox("Dual SIM", (0, 1), help="0 = No, 1 = Yes")
fc = st.number_input("Front Camera Megapixels", min_value=0, max_value=20, step=1)
four_g = st.selectbox("4G Support", (0, 1), help="0 = No, 1 = Yes")
int_memory = st.number_input("Internal Memory (GB)", min_value=2, max_value=128, step=1)
m_dep = st.slider("Mobile Depth (cm)", min_value=0.1, max_value=1.0, step=0.1)
mobile_wt = st.number_input("Mobile Weight (g)", min_value=50, max_value=300, step=10)
n_cores = st.number_input("Number of Cores", min_value=1, max_value=8, step=1)
pc = st.number_input("Primary Camera Megapixels", min_value=0, max_value=50, step=1)
px_height = st.number_input("Pixel Resolution Height", min_value=100, max_value=3000, step=100)
px_width = st.number_input("Pixel Resolution Width", min_value=100, max_value=3000, step=100)
ram = st.number_input("RAM (MB)", min_value=512, max_value=8000, step=128)
sc_h = st.number_input("Screen Height (cm)", min_value=5, max_value=20, step=1)
sc_w = st.number_input("Screen Width (cm)", min_value=2, max_value=20, step=1)
talk_time = st.number_input("Talk Time (hours)", min_value=2, max_value=24, step=1)
three_g = st.selectbox("3G Support", (0, 1), help="0 = No, 1 = Yes")
touch_screen = st.selectbox("Touch Screen", (0, 1), help="0 = No, 1 = Yes")
wifi = st.selectbox("WiFi Support", (0, 1), help="0 = No, 1 = Yes")

# Create a button for prediction
if st.button("Predict Price Range"):
    # Prepare input for the model
    features = np.array([[
        battery_power, blue, clock_speed, dual_sim, fc, four_g, int_memory, m_dep,
        mobile_wt, n_cores, pc, px_height, px_width, ram, sc_h, sc_w, talk_time,
        three_g, touch_screen, wifi
    ]])

    # Make a prediction
    prediction = model.predict(features)

    # Display the prediction result
    st.success(f"The predicted price range is: {prediction[0]}")